import { ArrowLeft, ArrowUpRight, Leaf, MapPin } from "lucide-react";
import { Link } from "react-router-dom";
import { BotanicalDivider } from "@/components/BotanicalDivider";

const villageImage = "https://images.pexels.com/photos/20223766/pexels-photo-20223766.jpeg";
const teaImage = "https://images.pexels.com/photos/5605/drink-leaf-leaves-green.jpg";
const flowerImage = "https://images.pexels.com/photos/16986600/pexels-photo-16986600.jpeg";

export default function About() {
  return <div>
    <section className="bg-[#e6ece4] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.9fr_1.1fr]"><div><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-foreground/55 hover:text-primary"><ArrowLeft size={15} /> Back to Elysara</Link><p className="eyebrow mt-12 text-primary">The Elysara story</p><h1 className="mt-5 max-w-xl text-6xl leading-[.96] sm:text-8xl">From the<br /><em className="font-normal text-primary">everyday rush</em><br />back to what’s real.</h1><p className="mt-8 max-w-md text-base leading-7 text-foreground/65">A story about two friends, one village, and the quiet wisdom that changed the way they wanted to live.</p></div><div className="relative h-[420px] overflow-hidden rounded-[2rem] sm:h-[560px]"><img src={villageImage} alt="People sorting fresh herbs outdoors" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-t from-secondary/45 to-transparent" /><div className="absolute bottom-6 left-6 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-white"><MapPin size={15} /> Where it began</div></div></div></section>
    <section className="photo-paper-leaves px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-4xl gap-8 text-lg leading-8 text-foreground/75"><p className="eyebrow text-primary">Before Elysara</p><p className="font-serif text-4xl leading-tight text-foreground sm:text-5xl">We were two friends with full calendars and very little room to breathe.</p><p>Our days were measured in meetings, deadlines and quick meals between calls. We were doing what we had set out to do, but somewhere along the way, feeling well had become something we kept postponing.</p><p>Then one weekend, we left the city for a small village. There, the pace was different. Herbs were gathered with the morning light. Food followed the seasons. People knew the land beneath their feet, and their health was not separate from nature — it was part of the same rhythm.</p><div className="my-6"><BotanicalDivider /></div><p className="font-serif text-3xl leading-tight text-secondary sm:text-4xl">That visit gave us a question we couldn’t shake: what if modern living could make room for those roots?</p></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid items-center gap-12 lg:grid-cols-[1.1fr_.9fr]"><div className="grid grid-cols-2 gap-4"><img src={teaImage} alt="Fresh leaves beside a cup of tea" className="mt-12 h-72 w-full rounded-[1.5rem] object-cover" /><img src={flowerImage} alt="Dried flowers prepared for an herbal blend" className="h-72 w-full rounded-[1.5rem] object-cover" /></div><div><p className="eyebrow text-primary">The idea became Elysara</p><h2 className="mt-5 text-5xl leading-tight sm:text-6xl">Bring the roots<br /><em className="font-normal text-primary">forward.</em></h2><p className="mt-7 text-base leading-7 text-muted-foreground">Elysara is our way of carrying that village lesson into the modern era. We make botanical blends that are beautiful enough to invite a pause, and thoughtful enough to become part of your everyday life.</p><p className="mt-5 text-base leading-7 text-muted-foreground">Not a perfect lifestyle. Not another list to keep up with. Just honest ingredients, small rituals and a gentler way to feel connected to yourself and the world around you.</p><Link to="/products" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-primary">Meet our first blends <ArrowUpRight size={15} /></Link></div></div></section>
    <section className="bg-secondary px-6 py-20 text-center text-secondary-foreground lg:px-10"><Leaf className="mx-auto text-accent" size={24} /><h2 className="mx-auto mt-5 max-w-xl text-4xl leading-tight sm:text-5xl">Here’s to making space for what keeps us well.</h2><Link to="/contact" className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-accent">Say hello <ArrowUpRight size={15} /></Link></section>
  </div>;
}
