import { ArrowLeft, ArrowUpRight, Leaf } from "lucide-react";
import { FormEvent, useState } from "react";
import { Link, useNavigate, useParams } from "react-router-dom";

export default function Auth() {
  const { mode = "login" } = useParams();
  const signup = mode === "signup";
  const navigate = useNavigate();
  const [submitted, setSubmitted] = useState(false);
  const handleSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); localStorage.setItem("elysara-member", "true"); setSubmitted(true); };
  return <section className="photo-paper-warm flex min-h-[72vh] items-center justify-center px-6 py-24"><div className="w-full max-w-md"><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-foreground/55 hover:text-primary"><ArrowLeft size={15} /> Back home</Link><div className="mt-10 rounded-[1.5rem] border border-border bg-background/85 p-8 shadow-sm backdrop-blur-sm sm:p-10"><span className="flex h-11 w-11 items-center justify-center rounded-full bg-secondary text-background"><Leaf size={18} /></span><p className="eyebrow mt-8 text-primary">Elysara circle</p><h1 className="mt-3 text-4xl">{signup ? "Create your account." : "Welcome back."}</h1>{submitted ? <div className="mt-8"><p className="text-base leading-7 text-muted-foreground">You’re all set. Your Elysara space is ready.</p><button type="button" onClick={() => navigate("/")} className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-primary">Continue home <ArrowUpRight size={15} /></button></div> : <form onSubmit={handleSubmit} className="mt-8 space-y-5"><label className="block"><span className="eyebrow text-muted-foreground">Email</span><input required type="email" className="mt-2 w-full border-b border-border bg-transparent px-0 py-3 text-sm outline-none focus:border-primary" placeholder="you@example.com" /></label>{signup && <label className="block"><span className="eyebrow text-muted-foreground">Name</span><input required className="mt-2 w-full border-b border-border bg-transparent px-0 py-3 text-sm outline-none focus:border-primary" placeholder="Your name" /></label>}<label className="block"><span className="eyebrow text-muted-foreground">Password</span><input required minLength={6} type="password" className="mt-2 w-full border-b border-border bg-transparent px-0 py-3 text-sm outline-none focus:border-primary" placeholder="At least 6 characters" /></label><button type="submit" className="flex w-full items-center justify-center gap-2 rounded-full bg-primary px-5 py-4 text-xs font-bold uppercase tracking-[0.14em] text-primary-foreground">{signup ? "Create account" : "Log in"} <ArrowUpRight size={15} /></button></form>}<p className="mt-8 text-center text-sm text-muted-foreground">{signup ? "Already a member?" : "New to Elysara?"} <Link to={signup ? "/login" : "/signup"} className="font-semibold text-primary hover:underline">{signup ? "Log in" : "Sign up"}</Link></p></div></div></section>;
}
