import { ArrowLeft, ArrowUpRight, Mail, MessageCircle, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

export default function Contact() {
  return <div>
    <section className="bg-[#e6ece4] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-7xl"><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-foreground/55 hover:text-primary"><ArrowLeft size={15} /> Back to Elysara</Link><div className="mt-16 grid gap-14 lg:grid-cols-[1fr_.8fr]"><div><p className="eyebrow text-primary">The garden gate is open</p><h1 className="mt-5 max-w-2xl text-6xl leading-[.96] sm:text-8xl">Let’s make<br /><em className="font-normal text-primary">something good.</em></h1><p className="mt-8 max-w-md text-base leading-7 text-foreground/65">Questions about our blends, a collaboration idea, or simply want to say hello? We’d love to hear from you.</p></div><div className="relative overflow-hidden rounded-[2rem] bg-[#dce7e2] p-8 sm:p-10"><Sparkles className="text-primary" size={23} /><p className="mt-12 max-w-sm font-serif text-3xl leading-tight">Good conversations are where thoughtful things begin.</p><div className="absolute -bottom-16 -right-10 h-48 w-48 rounded-full border border-secondary/20" /></div></div></div></section>
    <section className="photo-paper-warm px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-5xl"><p className="eyebrow text-primary">Reach us directly</p><div className="mt-10 grid gap-5 md:grid-cols-2"><a href="mailto:elysaraorganicsandlifestyle@gmail.com" className="group rounded-[1.5rem] border border-border bg-background/70 p-8 backdrop-blur-sm transition-transform hover:-translate-y-1"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-muted text-primary"><Mail size={21} /></span><p className="eyebrow mt-8 text-muted-foreground">Email</p><h2 className="mt-3 break-all font-serif text-2xl sm:text-3xl">elysaraorganicsandlifestyle@gmail.com</h2><span className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-primary">Write to us <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></a><a href="https://wa.me/918668525793" target="_blank" rel="noreferrer" className="group rounded-[1.5rem] border border-border bg-background/70 p-8 backdrop-blur-sm transition-transform hover:-translate-y-1"><span className="flex h-12 w-12 items-center justify-center rounded-full bg-muted text-primary"><MessageCircle size={21} /></span><p className="eyebrow mt-8 text-muted-foreground">WhatsApp</p><h2 className="mt-3 font-serif text-3xl">+91 8668525793</h2><span className="mt-8 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-primary">Start a chat <ArrowUpRight size={15} className="transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></span></a></div></div></section>
    <section className="px-6 py-20 text-center lg:px-10"><p className="eyebrow text-primary">A little note</p><h2 className="mx-auto mt-4 max-w-xl text-4xl leading-tight">We read every message with care.</h2><p className="mx-auto mt-5 max-w-md text-sm leading-7 text-muted-foreground">We’re a small, growing team, so replies may take a little time. Thank you for meeting us where we are.</p></section>
  </div>;
}
