import { ArrowLeft, ArrowUpRight, Check, Leaf, Sparkles } from "lucide-react";
import { Link } from "react-router-dom";

const productImages = {
  blue: "https://cdn.builder.io/api/v1/image/assets%2F4215d9916ba54932a9c5dfbeef662b8a%2Fa0882b20877849b1b43a1a55062cd1cc?format=webp&width=800&height=1200",
  coral: "https://cdn.builder.io/api/v1/image/assets%2F4215d9916ba54932a9c5dfbeef662b8a%2F674b3484bbdc407e90708352cd3afd1c?format=webp&width=800&height=1200",
};

type ProductDetailProps = {
  tone: "blue" | "coral";
  name: string;
  number: string;
  intro: string;
  ingredients: { name: string; note: string }[];
  benefits: { title: string; body: string }[];
};

export function ProductDetail({ tone, name, number, intro, ingredients, benefits }: ProductDetailProps) {
  const blue = tone === "blue";
  return <div>
    <section className={`relative overflow-hidden px-6 py-20 lg:px-10 lg:py-28 ${blue ? "bg-[#dce7e2]" : "bg-[#ead8cd]"}`}><div className="mx-auto grid max-w-7xl items-center gap-14 lg:grid-cols-[.85fr_1.15fr]"><div className="order-2 lg:order-1"><Link to="/products" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-foreground/55 hover:text-primary"><ArrowLeft size={15} /> All blends</Link><p className="eyebrow mt-12 text-primary">Floral tea · {number}</p><h1 className="mt-5 text-6xl leading-[.95] sm:text-8xl">{name}</h1><p className="mt-8 max-w-md text-lg leading-8 text-foreground/70">{intro}</p><div className="mt-10 flex items-center gap-3 text-xs font-bold uppercase tracking-[0.14em] text-secondary"><span className="h-2 w-2 rounded-full bg-primary" /> Caffeine-free botanical blend</div></div><div className="relative order-1 mx-auto w-full max-w-xl lg:order-2"><div className="absolute -inset-5 rounded-[2rem] border border-foreground/10" /><img src={productImages[tone]} alt={`${name} floral tea`} className="relative h-[380px] w-full rounded-[1.5rem] object-cover shadow-2xl sm:h-[520px]" /><div className="absolute bottom-5 left-5 rounded-full bg-background/90 px-4 py-2 text-[0.62rem] font-bold uppercase tracking-[0.15em] text-foreground/70 backdrop-blur">Elysara Organics</div></div></div></section>
    <section className="photo-paper-leaves px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl gap-16 lg:grid-cols-[.65fr_1.35fr]"><div><p className="eyebrow text-primary">What’s inside</p><h2 className="mt-4 text-5xl leading-tight">A garden,<br /><em className="font-normal text-primary">in every cup.</em></h2><p className="mt-6 max-w-xs text-sm leading-6 text-muted-foreground">Whole botanicals selected for their colour, character and the quiet ritual they create.</p><div className="mt-8 flex items-center gap-3 text-sm text-secondary"><Leaf size={17} /> Steep for 5–7 minutes</div></div><div className="grid gap-4 sm:grid-cols-3">{ingredients.map((ingredient) => <div key={ingredient.name} className="border-t border-border pt-5"><span className="flex h-9 w-9 items-center justify-center rounded-full bg-muted text-primary"><Check size={16} /></span><h3 className="mt-5 text-2xl">{ingredient.name}</h3><p className="mt-3 text-sm leading-6 text-muted-foreground">{ingredient.note}</p></div>)}</div></div></section>
    <section className="bg-background px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto max-w-4xl"><div className="text-center"><Sparkles className="mx-auto text-primary" size={21} /><p className="eyebrow mt-5 text-primary">The thoughtful cup</p><h2 className="mt-4 text-5xl sm:text-6xl">Why make it part<br /><em className="font-normal text-primary">of your ritual?</em></h2><p className="mx-auto mt-6 max-w-xl text-sm leading-7 text-muted-foreground">A closer look at the traditional uses and early research around the botanicals in {name}.</p></div><div className="mt-14 grid gap-10 sm:grid-cols-2">{benefits.map((benefit, index) => <article key={benefit.title} className="border-t border-border pt-6"><p className="eyebrow text-muted-foreground">0{index + 1} · Botanical note</p><h3 className="mt-3 text-3xl">{benefit.title}</h3><p className="mt-4 text-sm leading-7 text-muted-foreground">{benefit.body}</p></article>)}</div><p className="mx-auto mt-14 max-w-2xl border-t border-border pt-6 text-center text-xs leading-6 text-muted-foreground">These notes describe traditional uses and emerging research, not medical advice. Herbal teas can interact with medicines or conditions; check with a qualified healthcare professional if you have concerns.</p></div></section>
    <section className="bg-secondary px-6 py-16 text-center text-secondary-foreground lg:px-10"><p className="eyebrow text-accent">Keep exploring</p><h2 className="mt-4 text-4xl">Find your next ritual.</h2><Link to="/products" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.14em] text-accent">View all available blends <ArrowUpRight size={15} /></Link></section>
  </div>;
}

export function BlueVitalityPage() {
  return <ProductDetail tone="blue" name="Blue Vitality" number="01" intro="A vivid butterfly pea flower infusion lifted with rosemary and lemongrass — bright, botanical and made for a fresh start." ingredients={[{ name: "Butterfly pea", note: "A naturally blue flower with anthocyanin pigments and a softly earthy finish." }, { name: "Rosemary", note: "A fragrant evergreen herb that brings a resinous, aromatic depth." }, { name: "Lemongrass", note: "A clean citrus note that keeps the blend bright and refreshing." }]} benefits={[{ title: "A naturally vivid antioxidant cup", body: "Butterfly pea flower is rich in anthocyanins, the pigments that give it its deep blue colour. Early research is promising, but human evidence is still developing — so we love it first for its colour, flavour and caffeine-free pause." }, { title: "Bright, citrusy and easy to return to", body: "Rosemary and lemongrass have long been used in traditional food and wellness practices. Together they create a fresh aromatic profile that makes this blend feel especially good after a meal or during an afternoon reset." }]} />;
}

export function CrimsonBloomPage() {
  return <ProductDetail tone="coral" name="Crimson Bloom" number="02" intro="A ruby-red hibiscus infusion with rosemary and lemongrass — tart, fragrant and grounding for slower moments." ingredients={[{ name: "Hibiscus", note: "A jewel-toned flower with a bright, cranberry-like tartness." }, { name: "Rosemary", note: "A fragrant evergreen herb that adds a warm, herbal backbone." }, { name: "Lemongrass", note: "A light lemon lift that balances the deep floral character." }]} benefits={[{ title: "A ruby-red ritual with research behind it", body: "Hibiscus sabdariffa has been studied for its relationship with blood pressure. Meta-analyses suggest modest reductions in some adults, but results vary and the tea should never replace prescribed care." }, { title: "A fragrant, naturally caffeine-free pause", body: "Rosemary and lemongrass bring aromatic depth and a clean citrus finish. Their traditional use in food and herbal preparations makes this a beautifully simple blend to enjoy warm or over ice." }]} />;
}
