import { ArrowLeft, ArrowUpRight, Leaf } from "lucide-react";
import { Link } from "react-router-dom";
import { BotanicalDivider } from "@/components/BotanicalDivider";
import { ProductArt } from "@/components/ProductArt";

export default function FloralTea() {
  return <div>
    <section className="relative overflow-hidden bg-[#e6ece4] px-6 py-24 lg:px-10 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1fr_.8fr]"><div><Link to="/" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-foreground/55 hover:text-primary"><ArrowLeft size={15} /> Back to Elysara</Link><p className="eyebrow mt-12 text-primary">The floral collection</p><h1 className="mt-5 max-w-xl text-6xl leading-[.98] sm:text-8xl">Let your day<br /><em className="font-normal text-primary">unfold.</em></h1><p className="mt-8 max-w-md text-base leading-7 text-foreground/65">Delicate blooms, vivid colour and a little everyday magic. Our first two floral infusions are made to turn an ordinary pause into something worth remembering.</p></div><div className="relative mx-auto flex h-72 w-72 items-center justify-center rounded-full bg-[#f3efe3] sm:h-96 sm:w-96"><Leaf className="absolute right-10 top-10 text-secondary/30" size={34} /><svg viewBox="0 0 260 260" className="h-56 w-56 sm:h-72 sm:w-72" fill="none"><path d="M130 244C132 190 135 132 126 51" stroke="#526e58" strokeWidth="2"/><path d="M130 161C98 142 76 119 58 91M133 132C165 113 186 91 204 60" stroke="#526e58" strokeWidth="2"/><circle cx="126" cy="51" r="22" fill="#b8664d" fillOpacity=".65"/><circle cx="58" cy="91" r="17" fill="#d3977d" fillOpacity=".75"/><circle cx="204" cy="60" r="19" fill="#c47e68" fillOpacity=".7"/></svg></div></div></section>
    <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10 lg:py-32"><div className="grid gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><p className="eyebrow text-primary">Two ways to bloom</p><h2 className="mt-4 text-4xl leading-tight sm:text-5xl">Find your<br /><em className="font-normal text-primary">floral mood.</em></h2><p className="mt-6 max-w-xs text-sm leading-6 text-muted-foreground">Created with whole botanicals and a lighter touch. Steep slowly, sip mindfully.</p></div><div className="grid gap-6 sm:grid-cols-2"><Link to="/products/blue-vitality" className="group"><ProductArt tone="blue" compact /><div className="flex items-start justify-between border-b border-border py-5"><div><p className="eyebrow text-muted-foreground">Floral tea · 01</p><h3 className="mt-2 text-3xl">Blue Vitality</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Bright, gently citrusy and made for a fresh start.</p></div><ArrowUpRight className="text-primary transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div></Link><Link to="/products/crimson-bloom" className="group"><ProductArt tone="coral" compact /><div className="flex items-start justify-between border-b border-border py-5"><div><p className="eyebrow text-muted-foreground">Floral tea · 02</p><h3 className="mt-2 text-3xl">Crimson Bloom</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">Rich, rosy and grounding with a beautiful finish.</p></div><ArrowUpRight className="text-primary transition-transform group-hover:translate-x-1 group-hover:-translate-y-1" /></div></Link></div></div></section>
    <section className="bg-[#f0ebe1] px-6 py-20 text-center lg:px-10"><BotanicalDivider /><h2 className="mt-8 text-4xl">More petals are on the way.</h2><p className="mx-auto mt-4 max-w-md text-sm leading-6 text-muted-foreground">We’re tending to a few new floral favourites. Sign up to be the first to know when they bloom.</p><Link to="/" className="mt-7 inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.13em] text-primary">Return home <ArrowUpRight size={15} /></Link></section>
  </div>;
}
